# generated by datamodel-codegen:
#   filename:  chronicle-bridge.openapi.yaml
#   timestamp: 2026-08-27T04:56:08+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class EventType(Enum):
    npc_died = 'npc_died'
    crime_witnessed = 'crime_witnessed'


class GameEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_type: EventType = Field(
        ...,
        description='"npc_died" (docs/design/chronicle-bridge-death-extraction.md §2) or "crime_witnessed" (docs/design/chronicle-bridge- crime-witness-out.md §4) -- more kinds get added here when their own slice lands, never inferred from payload shape. npc_id is required when event_type is npc_died; witness_id/perpetrator_id/crime_type are required when event_type is crime_witnessed -- not expressible as JSON Schema `required` on this single flat object, so the listener/injection path is what actually enforces per-kind shape (docs/design/chronicle-bridge-crime-witness-out.md §4).\n',
    )
    gamets: float = Field(
        ...,
        description="Skyrim's in-game hours-elapsed clock (RE::Calendar's hours passed since new-game start) at the moment of death -- 1 tick = 1 gamets = 1 game-hour (ADR-0010). This, not wall_ts, is what places the event on the live run's timeline via `chronicle inject`'s existing --event JSON contract (chronicle/cli.py), which requires tick or gamets, never wall-clock time, for placement.\n",
    )
    wall_ts: float | None = Field(
        None,
        description='Unix epoch seconds when the plugin observed this event -- auxiliary metadata only (staleness/observability, same idiom as PositionSnapshot.wall_ts), never used for timeline placement.\n',
    )
    npc_id: str | None = Field(
        None,
        description='npc_died only. Same identity resolution as NpcPosition.id (design doc §2) -- a resolved Chronicle npc_id or the "<plugin>:<formid>" fallback. Never a raw FormID.\n',
    )
    cause: str | None = Field(
        'unknown',
        description='npc_died only. Fixed "unknown" for this slice (design doc §2, D2) -- RE::TESDeathEvent carries no structured cause code that\'s been verified against the compiled headers yet. NPCDied.cause is a plain string, not an enum, so richer detection can land later without a schema change.\n',
    )
    killer_id: str | None = Field(
        None,
        description='npc_died only. Same identity resolution as npc_id, when RE::TESDeathEvent::actorKiller resolves to another actor. Null if absent.',
    )
    location_id: str | None = Field(
        None,
        description='npc_died or crime_witnessed. The location the event occurred at, when resolved.',
    )
    witness_id: str | None = Field(
        None,
        description='crime_witnessed only (docs/design/chronicle-bridge-crime- witness-out.md §2). Same identity resolution as npc_id -- the NPC who observed the crime.\n',
    )
    perpetrator_id: str | None = Field(
        None,
        description='crime_witnessed only. Same identity resolution as npc_id -- who committed the crime.',
    )
    crime_type: str | None = Field(
        None,
        description='crime_witnessed only. Free-form crime-kind string (e.g. "assault", "theft", "trespassing") -- doubles as the belief\'s Claim.kind (design doc §2).\n',
    )
    victim_id: str | None = Field(
        None,
        description="crime_witnessed only. The crime's own victim, when there is a specific one; null means no specific human victim (property/bounty crime) or unknown -- always routes to the bystander/no-grudge cascade (design doc §1/§2).\n",
    )


class NpcPosition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description='The resolved Chronicle npc_id (e.g. "jarl_balgruuf") for the named cast, or the generic fallback identity "<plugin_name>:<local_form_id_hex>" for anyone not in the hand-maintained table (design doc §3, B3) -- never a raw FormID (architecture.md\'s FormID rule).\n',
    )
    name: str = Field(
        ...,
        description='The actor\'s in-game display name (e.g. "Idolaf Battle-Born"), read directly from the game -- independent of whether `id` resolved to a Chronicle npc_id or the generic fallback. Display-only (dashboard click-to-reveal); never used as a stable identity. Empty string if the game reports none.\n',
    )
    x: float = Field(
        ..., description='WhiterunWorld raw world-space X (no transform applied).'
    )
    y: float = Field(
        ..., description='WhiterunWorld raw world-space Y (no transform applied).'
    )


class PositionSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    wall_ts: float = Field(
        ..., description='Unix epoch seconds when the plugin sampled this snapshot.'
    )
    npcs: list[NpcPosition]
