# generated by datamodel-codegen:
#   filename:  chronicle-bridge.openapi.yaml
#   timestamp: 2026-08-24T20:03:18+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class NpcPosition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description='The resolved Chronicle npc_id (e.g. "jarl_balgruuf") for the named cast, or the generic fallback identity "<plugin_name>:<local_form_id_hex>" for anyone not in the hand-maintained table (design doc §3, B3) -- never a raw FormID (architecture.md\'s FormID rule).\n',
    )
    x: float = Field(
        ..., description='WhiterunWorld raw world-space X (no transform applied).'
    )
    y: float = Field(
        ..., description='WhiterunWorld raw world-space Y (no transform applied).'
    )


class PositionSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    wall_ts: float = Field(
        ..., description='Unix epoch seconds when the plugin sampled this snapshot.'
    )
    npcs: list[NpcPosition]
